controller_manager:
  ros__parameters:
    update_rate: 125  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    march_motor_controller_state_broadcaster:
      type: march_motor_controller_state_broadcaster/MotorControllerStateBroadcaster

march_motor_controller_state_broadcaster:
  ros__parameters:
    # If the one of the following joint names is in the xacro than the pdb will broadcast its motor controller info.
    possible_joints:
      - left_hip_fe
      - left_knee
      - right_hip_fe
      - right_knee


joint_trajectory_controller:
  ros__parameters:
    update_rate: 125
    joints:
      - left_hip_fe
      - left_knee
      - right_hip_fe
      - right_knee
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      - effort
    gains:
      left_hip_fe: {p: 75.0, i: 0.0, d: 10.0, i_clamp: 100.0 }
      left_knee: {p: 75.0, i: 0.0, d: 15.0, i_clamp: 100.0 }
      right_hip_fe: {p: 75.0, i: 0.0, d: 10.0, i_clamp: 100.0 }
      right_knee: {p: 75.0, i: 0.0, d: 15.0, i_clamp: 100.0 }


    #    state_publish_rate: 1000.0 # Defaults to 50
    #    action_monitor_rate: 20.0 # Defaults to 20
    allow_partial_joints_goal: false # Defaults to false
    #    open_loop_control: false
    allow_integration_in_goal_trajectories: true
    constraints:
      goal_time: 0.5 # Defaults to 0.0 (no goal time limit)
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      left_hip_fe:
        margin_soft_limit_error: 0.5
        trajectory: 2.0
        goal: 2.0
      left_knee:
        margin_soft_limit_error: 0.5
        trajectory: 2.0
        goal: 2.0
      right_hip_fe:
        margin_soft_limit_error: 0.5
        trajectory: 2.0
        goal: 2.0
      right_knee:
        margin_soft_limit_error: 0.5
        trajectory: 2.0
        goal: 2.0
