controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    march_motor_controller_state_broadcaster:
      type: march_motor_controller_state_broadcaster/MotorControllerStateBroadcaster

    march_joint_position_controller:
      type: forward_command_controller/ForwardCommandController

march_motor_controller_state_broadcaster:
  ros__parameters:
    possible_joints:
      # - linear_joint
      - rotational_joint
    interface_name: position

march_joint_position_controller:
  ros__parameters:
    joints:
      # - linear_joint
      - rotational_joint
    interface_name: position
