march:
  controller:
    joint_state:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    temperature_sensor:
      type: march_temperature_sensor_controller/MarchTemperatureSensorController
      publish_rate: 1
    pdb_state:
      type: march_pdb_state_controller/MarchPdbStateController
      publish_rate: 50
    trajectory:
      type: effort_controllers/JointTrajectoryController
      joints:
        - linear_joint
      gains:
        linear_joint: {p: 150, i: 0, d: 10, i_clamp: 100, publish_state: true, antiwindup: true}

      constraints:
        linear_joint:
          margin_soft_limit_error: 0.5
          trajectory: 0.305
          goal: 0.305
