controller_manager:
  ros__parameters:
    update_rate: 125  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    march_motor_controller_state_broadcaster:
      type: march_motor_controller_state_broadcaster/MotorControllerStateBroadcaster

    march_joint_position_controller:
      type: forward_command_controller/ForwardCommandController

march_motor_controller_state_broadcaster:
  ros__parameters:
    # If the one of the following joint names is in the xacro than the pdb will broadcast its motor controller info.
    possible_joints:
      - rotational_joint

march_joint_position_controller:
  ros__parameters:
    joints:
      - rotational_joint
    interface_name: position