ik_solver_point_evaluator:
  ros__parameters:
      desired_left_foot_position:
        x: 0.2
        y: 0.165
        z: -0.5
      desired_right_foot_position:
        x: 0.2
        y: -0.165
        z: -0.5