ik_solver:
  ros__parameters:
    state_estimator_time_offset: 20e-3
    joint_trajectory_controller_period: 5e-3
    convergence_threshold: 1e-3
    max_iterations: 100
    integral_dt: 5e-3
    joint:
      names:
      - left_hip_aa
      - left_hip_fe
      - left_knee
      - left_ankle_dpf
      - left_ankle_ie
      - right_hip_aa
      - right_hip_fe
      - right_knee
      - right_ankle_dpf
      - right_ankle_ie
      active:
      - true  # left_hip_aa
      - true  # left_hip_fe
      - true  # left_knee
      - true  # left_ankle_dpf
      - false # left_ankle_ie
      - true  # right_hip_aa
      - true  # right_hip_fe
      - true  # right_knee
      - true  # right_ankle_dpf
      - false # right_ankle_ie
      limits:
        positions:
          # upper: [10.0, 112.5, 125.0, 10.0, 10.0, 112.5, 125.0, 10.0]
          # lower: [-15.0, -10.0, 0.0, -25.0, -15.0, -10.0, 0.0, -25.0]
          # upper: [8.75, 106.25, 118.75, 8.25, 8.75, 106.25, 118.75, 8.25]
          # lower: [-13.75, -3.875, 6.25, -23.25, -13.75, -3.875, 6.25, -23.25]
          # upper: [7.5, 110.0, 112.5, 4.0, 10.0, 7.5, 110.0, 112.5, 4.0, 10.0]
          # lower: [-12.5, 2.25, 12.5, -18.0, -10.0, -12.5, 2.25, 12.5, -18.0, -10.0]
          upper: [7.0, 112.0, 122.0, 17.0, 5.0, 7.0, 112.0, 122.0, 17.0, 5.0]
          lower: [-17.0, -17.0, 3.0, -25.0, -5.0, -17.0, -17.0, 3.0, -25.0, -5.0]
        velocities:
          lower: [-100.0, -115.6, -243.6, -130.1, -100.0, -100.0, -115.6, -243.6, -130.1, -100.0]
          upper: [ 100.0,  67.16,  208.9,  100.3, 100.0,  100.0,  67.16,  208.9,  100.3, 100.0]
    task_names:
    # - posture
    - motion
    # - stability # Comment to disable stability task
    motion:
      reference_frame: "body"
      nodes: ["L_ankle", "R_ankle"]
      m: 12
      n: 8
      kp: [100.0, 300.0, 200.0, 10.0, 0.0, 0.0, 100.0, 300.0, 200.0, 10.0, 0.0, 0.0]
      kd: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      ki: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      damp_coeff: 1e-12
    stability:
      reference_frame: "inertial"
      nodes: ["zmp"]
      m: 6
      n: 8
      kp: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      kd: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      ki: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      damp_coeff: 1e-12
    posture:
      reference_frame: "body"
      nodes: ["L_ankle", "R_ankle"]
      m: 12
      n: 8
      kp: [0.0, 0.0, 0.0, 10.0, 0.0, 0.0, 0.0, 0.0, 0.0, 10.0, 0.0, 0.0]
      kd: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      ki: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      damp_coeff: 1e-12
