ik_solver:
  ros__parameters:
    state_estimator_time_offset: 50e-3
    joint_trajectory_controller_period: 1e-3
    convergence_threshold: 1e-6
    max_iterations: 100
    dt: 5e-3
    joint:
      names: ["left_hip_aa", "left_hip_fe", "left_knee", "left_ankle", "right_hip_aa", "right_hip_fe", "right_knee", "right_ankle"]
      limits:
        positions:
          upper: [10.0, 112.5, 125.0, 10.0, 10.0, 112.5, 125.0, 10.0]
          lower: [-15.0, -10.0, 0.0, -25.0, -15.0, -10.0, 0.0, -25.0]
        velocities:
          lower: [-100.0, -115.6, -243.6, -130.1, -100.0, -115.6, -243.6, -130.1]
          upper: [ 100.0,  67.16,  208.9,  100.3,  100.0,  67.16,  208.9,  100.3]
    task_names: ["motion"]
    motion:
      nodes: ["left_ankle", "right_ankle"]
      m: 6
      n: 8
      kp: [50.0, 100.0, 100.0, 50.0, 100.0, 100.0]
      kd: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      ki: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      damp_coeff: 1e-4