ik_solver:
  ros__parameters:
    state_estimator_time_offset: 20e-3
    joint_trajectory_controller_period: 5e-3
    convergence_threshold: 1e-4
    max_iterations: 100000
    integral_dt: 1e-4
    joint:
      names:
      - left_hip_aa
      - left_hip_fe
      - left_knee
      - left_ankle_dpf
      - left_ankle_ie
      - right_hip_aa
      - right_hip_fe
      - right_knee
      - right_ankle_dpf
      - right_ankle_ie
      active:
      - true  # left_hip_aa
      - true  # left_hip_fe
      - true  # left_knee
      - true  # left_ankle_dpf
      - false # left_ankle_ie
      - true  # right_hip_aa
      - true  # right_hip_fe
      - true  # right_knee
      - true  # right_ankle_dpf
      - false # right_ankle_ie
      limits:
        positions:
          upper: [10.0, 115.0, 125.0, 20.0, 8.0, 10.0, 115.0, 125.0, 20.0, 8.0]
          lower: [-20.0, -20.0, 0.0, -28.0, -8.0, -20.0, -20.0, 0.0, -28.0, -8.0]
          soft: 3.0
        velocities:
          lower: [-100.0, -115.6, -243.6, -130.1, -100.0, -100.0, -115.6, -243.6, -130.1, -100.0]
          upper: [ 100.0,  67.16,  208.9,  100.3, 100.0,  100.0,  67.16,  208.9,  100.3, 100.0]
    task:
      names:
      - posture
      - motion
      - stability
      motion:
        kp: [25.0, 25.0, 25.0, 25.0, 25.0, 25.0]
        kd: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        ki: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        convergence_threshold: 1e-4
        damp_coeff: 1e-3
      stability:
        kp: [5.0, 15.0]
        kd: [0.0, 0.0]
        ki: [0.0, 0.0]
        convergence_threshold: 1e-2
        damp_coeff: 1e-12
      posture:
        kp: [25.0, 25.0]
        kd: [0.0, 0.0]
        ki: [0.0, 0.0]
        convergence_threshold: 1e-2
        damp_coeff: 1e-3
