ik_solver:
  ros__parameters:
    state_estimator_time_offset: 30e-3
    joint_trajectory_controller_period: 5e-3
    convergence_threshold: 1e-4
    max_iterations: 100000
    integral_dt: 1e-3
    joint:
      names:
      - left_hip_aa
      - left_hip_fe
      - left_knee
      - left_ankle_dpf
      - left_ankle_ie
      - right_hip_aa
      - right_hip_fe
      - right_knee
      - right_ankle_dpf
      - right_ankle_ie
      active:
      - true  # left_hip_aa
      - true  # left_hip_fe
      - true  # left_knee
      - true  # left_ankle_dpf
      - false # left_ankle_ie
      - true  # right_hip_aa
      - true  # right_hip_fe
      - true  # right_knee
      - true  # right_ankle_dpf
      - false # right_ankle_ie
      limits:
        positions:
          upper: [10.0, 115.0, 125.0, 20.0, 8.0, 10.0, 115.0, 125.0, 20.0, 8.0]
          lower: [-20.0, -20.0, 0.0, -28.0, -8.0, -20.0, -20.0, 0.0, -28.0, -8.0]
          soft: 5.0
        velocities:
          lower: [-100.0, -115.6, -243.6, -130.1, -100.0, -100.0, -115.6, -243.6, -130.1, -100.0]
          upper: [ 100.0,  67.16,  208.9,  100.3, 100.0,  100.0,  67.16,  208.9,  100.3, 100.0]
    task_names:
    # - posture
    - motion
    # - left_foot
    # - right_foot
    # - stability # Comment to disable stability task
    motion:
      reference_frame: "body"
      joint_indices: [4, 9]
      m: 12
      n: 10
      kp: [25.0, 25.0, 25.0, 0.0, 10.0, 0.0, 25.0, 25.0, 25.0, 0.0, 10.0, 0.0]
      kd: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      ki: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      damp_coeff: 1e-6
    # left_foot:
    #   reference_frame: "body"
    #   joint_indices: [4]
    #   m: 6
    #   n: 10
    #   kp: [30.0, 4.0, 30.0, 0.0, 0.0, 0.0]
    #   kd: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    #   ki: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    #   damp_coeff: 1e-3
    # right_foot:
    #   reference_frame: "body"
    #   joint_indices: [9]
    #   m: 6
    #   n: 10
    #   kp: [30.0, 4.0, 30.0, 0.0, 0.0, 0.0]
    #   kd: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    #   ki: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    #   damp_coeff: 1e-3
    # stability:
    #   reference_frame: "inertial"
    #   joint_indices: [4, 9]
    #   m: 6
    #   n: 8
    #   kp: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    #   kd: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    #   ki: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    #   damp_coeff: 1e-12
    posture:
      reference_frame: "body"
      joint_indices: [4, 9]
      m: 12
      n: 10
      kp: [0.0, 0.0, 0.0, 0.0, 3.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.0, 0.0]
      kd: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      ki: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      damp_coeff: 1e-3
