ik_solver:
  ros__parameters:
    joint_trajectory_controller_period: 5e-3
    max_iterations: 100000
    integral_dt: 1e-5
    joint:
      names:
      - left_hip_aa
      - left_hip_fe
      - left_knee
      - left_ankle_dpf
      - left_ankle_ie
      - right_hip_aa
      - right_hip_fe
      - right_knee
      - right_ankle_dpf
      - right_ankle_ie
      active:
      - true  # left_hip_aa
      - true  # left_hip_fe
      - true  # left_knee
      - true  # left_ankle_dpf
      - false # left_ankle_ie
      - true  # right_hip_aa
      - true  # right_hip_fe
      - true  # right_knee
      - true  # right_ankle_dpf
      - false # right_ankle_ie
      limits:
        positions:
          upper: [10.0, 115.0, 125.0, 16.0, 8.0, 10.0, 115.0, 125.0, 16.0, 8.0]   # deg
          lower: [-20.0, -20.0, 0.0, -23.0, -8.0, -20.0, -20.0, 0.0, -23.0, -8.0] # deg
          soft: [1.5, 6.76, 6.25, 3.0, 0.0, 1.5, 6.76, 6.25, 3.0, 0.0]  # deg
        velocities:
          upper: [ 50.0,  119.82,  236.16,  140.04, 0.0,  50.0,  119.82,  236.16,  140.04, 0.0]     # deg/s
          lower: [-50.0, -80.10, -200.05, -100.16, 0.0, -50.0, -80.10, -200.05, -100.16, 0.0]   # deg/s
          multiplier: 1.0
    task:
      names:
      - posture
      - motion
      - stability
      motion:
        kp: [75.0, 80.0, 100.0, 75.0, 80.0, 100.0]
        kd: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
        ki: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        convergence_threshold: 1e-6   # m
        damp_coeff: 1e-4
        weight: 1.0
      stability:
        kp: [2.5, 2.5]
        kd: [0.0, 0.0]
        ki: [0.0, 0.0]
        convergence_threshold: 1e-4
        damp_coeff: 1e-3
        weight: 1.0
      posture:
        kp: [100.0, 100.0]
        kd: [1.0, 1.0]
        ki: [0.0, 0.0]
        convergence_threshold: 1e-3   # rad
        damp_coeff: 1e-4
        weight: 1.0