#!/usr/bin/env python


from odrive_interface.odrive_motor import OdriveMotor


if __name__ == '__main__':
    odrive_motor = OdriveMotor.create_odrive('2084387E304E', 'axis0')
    print('odrive 2084387E304E has voltage: {vt}'.format(vt=odrive_motor.voltage))
