gaits:
  home: {home_sit: MIV_ankle_2.5, home_stand: MIV_ankle_2.5}
  ramp_door_slope_up: {right_open: MV_RD_slopeup_rightopen_v1, left_open: MV_RD_slopeup_leftopen_v1,
                       right_swing: MV_RD_slopeup_rightswing_v1, left_swing: MV_RD_slopeup_leftswing_v1,
                       right_close: MV_RD_slopeup_rightclose_v1, left_close: MV_RD_slopeup_leftclose_v1}
  ramp_door_slope_down: {right_open: MV_RD_slopedown_rightopen_v2, left_open: MV_RD_slopedown_leftopen_v2,
                         right_swing: MV_RD_slopedown_rightswing_v1, left_swing: MV_RD_slopedown_leftswing_v1,
                         right_close: MV_RD_slopedown_rightclose_v1, left_close: MV_RD_slopedown_leftclose_v1}
  ramp_door_last_step: {right_open: MV_RD_laststep_rightopen_v2, left_close: MV_RD_laststep_leftclose_v2}
  rough_terrain_high_step: {right_open: MV_RT_highstep_rightopen_v6, left_close: MV_RT_highstep_leftclose_v8}
  rough_terrain_middle_steps: {right_open: MV_RT_middlestep_rightopen_v2, left_swing: MV_RT_middlestep_leftswing_v2,
                               right_swing: MV_RT_middlestep_rightswing_v2, left_close: MV_RT_middlestep_leftclose_v3}
  rough_terrain_first_middle_step: {right_open: MV_RT_first_middlestep_rightopen_v1,
                                    left_close: MV_RT_first_middlestep_leftclose_v1}
  rough_terrain_second_middle_step: {right_open: MV_RT_second_middlestep_rightopen_v1,
                                     left_close: MV_RT_second_middlestep_leftclose_v1}
  rough_terrain_third_middle_step: {right_open: MV_RT_third_middlestep_rightopen_v1,
                                    left_close: MV_RT_third_middlestep_leftclose_v1}
  walk: {right_open: MV_walk_rightopen_v3, left_swing: MV_walk_leftswing_v2, right_swing: MV_walk_rightswing_v2,
         left_close: MV_walk_leftclose_v3, right_close: MV_walk_rightclose_v3}
  single_step_normal: {right_open: MIV_final, left_close: MIV_final}
  tilted_path_first_start: {left_open: MV_TPstart1_leftopen_v1, right_close: MV_TPstart1_rightclose_v1}
  tilted_path_second_start: {left_open: MV_TPstart2_leftopen_v1, right_close: MV_TPstart2_rightclose_v1}
  tilted_path_first_end: {left_open: MV_TPend1_leftopen_v1, right_close: MV_TPend1_rightclose_v1}
  tilted_path_second_end: {left_open: MV_TPend2_leftopen_v1, right_close: MV_TPend2_rightclose_v1}
  tilted_path_straight_start_right: {right_open: MV_TPstraight_rightopen_v1, left_close: MV_TPstraight_leftclose_v1}
  tilted_path_straight_start_left: {left_open: MV_TPstraight_leftopen_v1, right_close: MV_TPstraight_rightclose_v1}
  stairs_up: {right_open: MV_stairsup_rightopen_v2, left_swing: MV_stairsup_leftswing_v2,
              right_swing: MV_stairsup_rightswing_v2, left_close: MV_stairsup_leftclose_v2,
              right_close: MV_stairsup_rightclose_v2}
  stairs_down: {right_open: MV_stairsdown_rightopen_v2, left_swing: MV_stairsdown_leftswing_v2,
              right_swing: MV_stairsdown_rightswing_v2, left_close: MV_stairsdown_leftclose_v2,
              right_close: MV_stairsdown_rightclose_v2}