gaits:
  home: {home_sit: MIV_ankle_2.5, home_stand: MIV_ankle_2.5}
  rough_terrain_high_step: {right_open: MV_RT_highstep_rightopen_v1, left_close: MV_RT_highstep_leftclose_v1}
  rough_terrain_middle_steps: {right_open: MV_RT_middlestep_rightopen_v1, left_swing: MV_RT_middlestep_leftswing_v1,
                             right_swing: MV_RT_middlestep_rightswing_v1, left_close: MV_RT_middlestep_leftclose_v1}
