gaits:
  test_joint_gait:
    perform_test: perform_test_v6
  test_joint_gait_continuous:
    perform_test: perform_test_v6
    wait_test: wait_test_v6
positions:
  setup:
    gait_type: ''
    joints:
      rotational_joint: 0.0
