---
stages:
    - Generating
    - Executing

Generating pipeline:
  stage: Generating
  image: registry.gitlab.com/project-march/march/generate-pipeline:latest
  script: /usr/src/app/docker/gcip.sh
  artifacts:
    paths:
      - generated-config.yml

Running pipeline:
  stage: Executing
  needs:
    - Generating pipeline
  trigger:
    include:
      - artifact: generated-config.yml
        job: Generating pipeline
    strategy: depend
