# DUMMY GAINS FOR TESTING, ALL NUMERICAL VALUES OF THE DEFAULT GAINS YAML ARE INCREMENTED BY 0.5 
joints:
  left_ankle_dpf:
    constant_gains: [1.5, 2.5, 3.5]
    joint_angle_ranges: 
      - range: [-.inf, 1.0]
        gains: [1.5, 2.5, 3.5]
      - range: [1.0, 1.5]
        gains: [4.5, 5.5, 6.5]
      - range: [1.5, .inf]
        gains: [7.5, 8.5, 9.5]
  left_hip_aa:
    constant_gains: [2.5, 3.5, 4.5] 
    joint_angle_ranges: 
      - range: [-.inf, 1.0]
        gains: [1.5, 2.5, 3.5]
      - range: [1.0, 1.5]
        gains: [4.5, 5.5, 6.5]
      - range: [1.5, .inf]
        gains: [7.5, 8.5, 9.5]
  left_hip_fe:
    constant_gains: [3.5, 4.5, 5.5]
    joint_angle_ranges: 
      - range: [-.inf, 1.0]
        gains: [1.5, 2.5, 3.5]
      - range: [1.0, 1.5]
        gains: [4.5, 5.5, 6.5]
      - range: [1.5, .inf]
        gains: [7.5, 8.5, 9.5]
  left_knee_fe:
    constant_gains: [4.5, 5.5, 6.5]
    joint_angle_ranges: 
      - range: [-.inf, 1.0]
        gains: [1.5, 2.5, 3.5]
      - range: [1.0, 1.5]
        gains: [4.5, 5.5, 6.5]
      - range: [1.5, .inf]
        gains: [7.5, 8.5, 9.5]
  right_ankle_dpf:
    constant_gains: [5.5, 6.5, 7.5]
    joint_angle_ranges: 
      - range: [-.inf, 1.0]
        gains: [1.5, 2.5, 3.5]
      - range: [1.0, 1.5]
        gains: [4.5, 5.5, 6.5]
      - range: [1.5, .inf]
        gains: [7.5, 8.5, 9.5]
  right_hip_aa:
    constant_gains: [6.5, 7.5, 8.5]
    joint_angle_ranges: 
      - range: [-.inf, 1.0]
        gains: [1.5, 2.5, 3.5]
      - range: [1.0, 1.5]
        gains: [4.5, 5.5, 6.5]
      - range: [1.5, .inf]
        gains: [7.5, 8.5, 9.5]
  right_hip_fe:
    constant_gains: [7.5, 8.5, 9.5]
    joint_angle_ranges: 
      - range: [-.inf, 1.0]
        gains: [1.5, 2.5, 3.5]
      - range: [1.0, 1.5]
        gains: [4.5, 5.5, 6.5]
      - range: [1.5, .inf]
        gains: [7.5, 8.5, 9.5]
  right_knee_fe:
    constant_gains: [8.5, 9.5, 10.5]
    joint_angle_ranges: 
      - range: [-.inf, 1.0]
        gains: [1.5, 2.5, 3.5]
      - range: [1.0, 1.5]
        gains: [4.5, 5.5, 6.5]
      - range: [1.5, .inf]
        gains: [7.5, 8.5, 9.5]
