controller_manager:
  ros__parameters:
    update_rate: 125  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    update_rate: 125
    joints:
      - linear_joint
    
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort

    gains:
      linear_joint: {p: 150.0, i: 0.0, d: 10.0, i_clamp: 100.0}
    constraints:
      linear_joint:
        margin_soft_limit_error: 0.5
        trajectory: 0.305
        goal: 0.305
