height_bounds:
  # all values represent height in meters
  lower_bound: 0.0
  upper_bound: 0.2 # interpolate up to 20 cm, dummy value
torque_bounds:
  # all values represent torque in Nm
  lower_bound: 5.0 # maximum ankle torque for the stance leg, dummy value for now
  upper_bound: 0.0 
joints:
  # all values represent ratios in percentage points
  left_ankle_dpf:
    minimum_torque: 0.0
    maximum_torque: 0.3 
    constant_torque_weight: 0.2
  left_hip_aa:
    minimum_torque: 0.0
    maximum_torque: 0.2
    constant_torque_weight: 0.5
  left_hip_fe:
    minimum_torque: 0.0
    maximum_torque: 0.1
    constant_torque_weight: 0.4
  left_knee:
    minimum_torque: 0.0
    maximum_torque: 0.9
    constant_torque_weight: 0.1
  right_ankle_dpf:
    minimum_torque: 0.0
    maximum_torque: 0.3
    constant_torque_weight: 0.2
  right_hip_aa:
    minimum_torque: 0.0
    maximum_torque: 0.2
    constant_torque_weight: 0.5
  right_hip_fe:
    minimum_torque: 0.0
    maximum_torque: 0.1
    constant_torque_weight: 0.4
  right_knee:
    minimum_torque: 0.0
    maximum_torque: 0.1
    constant_torque_weight: 0.1
