gaits:
  walk:
    right_open: MV_walk_rightopen_v3
    left_swing: MV_walk_leftswing_v2
    right_swing: MV_walk_rightswing_v2
    left_close: MV_walk_leftclose_v3
    right_close: MV_walk_rightclose_v3
  ik_test:
    swing: forward_swing
  ik_test_multiple_subgaits:
    swing_up: forward_swing_simple
    swing_down: forward_swing_simple
positions:
  stand:
    gait_type: walk_like
    joints:
      left_ankle: 0.0
      left_hip_aa: 0.0349
      left_hip_fe: 0.0
      left_knee: 0.0
      right_ankle: 0.0
      right_hip_aa: 0.0349
      right_hip_fe: 0.0
      right_knee: 0.0
  idle_1:
    gait_type: walk_like
    joints:
      left_ankle: 0.0436
      left_hip_aa: 0.0873
      left_hip_fe: -0.0873
      left_knee: 0.0
      right_ankle: 0.1309
      right_hip_aa: -0.0524
      right_hip_fe: 0.5236
      right_knee: 0.8203
  idle_2:
    gait_type: walk_like
    joints:
      left_ankle: 0.0436
      left_hip_aa: 0.0
      left_hip_fe: 1.5708
      left_knee: 1.7453
      right_ankle: 0.0436
      right_hip_aa: 0.0
      right_hip_fe: 1.5708
      right_knee: 1.7453
  idle_3:
    gait_type: walk_like
    joints:
      left_ankle: 0.0436
      left_hip_aa: 0.0
      left_hip_fe: -0.0873
      left_knee: 0.0
      right_ankle: 0.0436
      right_hip_aa: 0.0
      right_hip_fe: 0.1745
      right_knee: 0.4363
  idle_4:
    gait_type: walk_like
    joints:
      left_ankle: -0.2618
      left_hip_aa: 0.0
      left_hip_fe: -0.0873
      left_knee: 0.0
      right_ankle: -0.2618
      right_hip_aa: 0.0
      right_hip_fe: -0.0873
      right_knee: 0.0
  sit:
    gait_type: walk_like
    joints:
      left_ankle: 0.0436
      left_hip_aa: 0.0
      left_hip_fe: 1.2217
      left_knee: 1.5708
      right_ankle: 0.0436
      right_hip_aa: 0.0
      right_hip_fe: 1.2217
      right_knee: 1.5708
  idle_6:
    gait_type: walk_like
    joints:
      left_ankle: 0.0436
      left_hip_aa: 0.0
      left_hip_fe: 0.1745
      left_knee: 0.4363
      right_ankle: 0.0436
      right_hip_aa: 0.0
      right_hip_fe: -0.0873
      right_knee: 0.0
  idle_7:
    gait_type: walk_like
    joints:
      left_ankle: 0.1309
      left_hip_aa: -0.0524
      left_hip_fe: 0.5236
      left_knee: 0.8203
      right_ankle: 0.0436
      right_hip_aa: 0.0873
      right_hip_fe: -0.0873
      right_knee: 0.0
  idle_8:
    gait_type: walk_like
    joints:
      left_ankle: 0.0436
      left_hip_aa: 0.1222
      left_hip_fe: -0.0873
      left_knee: 0.0
      right_ankle: 0.0436
      right_hip_aa: -0.0873
      right_hip_fe: 0.6109
      right_knee: 0.9076
  idle_9:
    gait_type: walk_like
    joints:
      left_ankle: 0.0436
      left_hip_aa: -0.0873
      left_hip_fe: 0.6109
      left_knee: 0.9076
      right_ankle: 0.0436
      right_hip_aa: 0.1222
      right_hip_fe: -0.0873
      right_knee: 0.0
  idle_10:
    gait_type: walk_like
    joints:
      left_ankle: 0.0436
      left_hip_aa: 0.0
      left_hip_fe: -0.0873
      left_knee: 0.0
      right_ankle: 0.0436
      right_hip_aa: 0.0
      right_hip_fe: 0.4014
      right_knee: 0.6981
  idle_11:
    gait_type: walk_like
    joints:
      left_ankle: 0.0436
      left_hip_aa: 0.0
      left_hip_fe: 0.4014
      left_knee: 0.6981
      right_ankle: 0.0436
      right_hip_aa: 0.0
      right_hip_fe: -0.0873
      right_knee: 0.0
