gaits:
  ramp_door_slope_down_fixed:
    left_close: MV_RD_slopedown_fixed_leftclose_v1
    left_swing: MV_RD_slopedown_fixed_leftswing_v1
    right_open: MV_RD_slopedown_fixed_rightopen_v1
    right_swing: MV_RD_slopedown_fixed_rightswing_v1
  ramp_door_slope_down_single:
    left_close: MV_RD_slopedownsingle_leftclose_v1
    right_open: MV_RD_slopedownsingle_rightopen_v1
  rough_terrain_first_middle_step:
    left_close: MV_RT_first_middlestep_leftclose_v2
    right_open: MV_RT_first_middlestep_rightopen_v2
  rough_terrain_high_step:
    left_close: MV_RT_highstep_leftclose_v8
    right_open: MV_RT_highstep_rightopen_v6
  rough_terrain_middle_steps:
    left_close: MV_RT_middlestep_leftclose_v3
    left_swing: MV_RT_middlestep_leftswing_v2
    right_open: MV_RT_middlestep_rightopen_v2
    right_swing: MV_RT_middlestep_rightswing_v2
  rough_terrain_second_middle_step:
    left_close: MV_RT_second_middlestep_leftclose_v1
    right_open: MV_RT_second_middlestep_rightopen_v1
  rough_terrain_third_middle_step:
    left_close: MV_RT_third_middlestep_leftclose_v1
    right_open: MV_RT_third_middlestep_rightopen_v1
  single_step_normal:
    left_close: MIV_final
    right_open: MIV_final
  tilted_path_first_end:
    left_open: MV_TPend1_leftopen_v1
    right_close: MV_TPend1_rightclose_v1
  tilted_path_first_start:
    left_open: MV_TPstart1_leftopen_v1
    right_close: MV_TPstart1_rightclose_v1
  tilted_path_left_flexed_knee_step:
    left_close: MV_TP_left_flexed_knee_step_leftclose_v1
    right_open: MV_TP_left_flexed_knee_step_rightopen_v1
  tilted_path_left_knee_bend:
    right_open: MV_TP_left_kneebend_rightopen_v5
  tilted_path_left_single_step:
    left_close: MV_TP_left_singlestep_leftclose_v5
    right_open: MV_TP_left_singlestep_rightopen_v5
  tilted_path_left_straight_end:
    left_open: MV_TP_left_straightend_leftopen_v5
    right_close: MV_TP_left_straightend_rightclose_v5
  tilted_path_left_straight_start:
    left_close: MV_TP_left_straightstart_leftclose_v5
    right_open: MV_TP_left_straightstart_rightopen_v5
  tilted_path_right_flexed_knee_step:
    left_open: MV_TP_right_flexed_knee_step_leftopen_v1
    right_close: MV_TP_right_flexed_knee_step_rightclose_v1
  tilted_path_right_knee_bend:
    right_open: MV_TP_right_kneebend_rightopen_v5
  tilted_path_right_single_step:
    left_open: MV_TP_right_singlestep_leftopen_v5
    right_close: MV_TP_right_singlestep_rightclose_v5
  tilted_path_right_straight_end:
    left_close: MV_TP_right_straightend_leftclose_v5
    right_open: MV_TP_right_straightend_rightopen_v5
  tilted_path_right_straight_start:
    left_open: MV_TP_right_straightstart_leftopen_v5
    right_close: MV_TP_right_straightstart_rightclose_v5
  tilted_path_second_end:
    left_open: MV_TPend2_leftopen_v1
    right_close: MV_TPend2_rightclose_v1
  tilted_path_second_start:
    left_open: MV_TPstart2_leftopen_v1
    right_close: MV_TPstart2_rightclose_v1
  tilted_path_straight_start_left:
    left_open: MV_TPstraight_leftopen_v1
    right_close: MV_TPstraight_rightclose_v1
  tilted_path_straight_start_right:
    left_close: MV_TPstraight_leftclose_v1
    right_open: MV_TPstraight_rightopen_v1
positions:
  idle_6:
    gait_type: walk_like
    joints:
      left_ankle: 0.0436
      left_hip_aa: 0.0
      left_hip_fe: 0.1745
      left_knee: 0.4363
      right_ankle: 0.0436
      right_hip_aa: 0.0
      right_hip_fe: -0.0873
      right_knee: 0.0
  idle_7:
    gait_type: walk_like
    joints:
      left_ankle: 0.1309
      left_hip_aa: -0.0524
      left_hip_fe: 0.5236
      left_knee: 0.8203
      right_ankle: 0.0436
      right_hip_aa: 0.0873
      right_hip_fe: -0.0873
      right_knee: 0.0
  idle_8:
    gait_type: walk_like
    joints:
      left_ankle: 0.0436
      left_hip_aa: 0.1222
      left_hip_fe: -0.0873
      left_knee: 0.0
      right_ankle: 0.0436
      right_hip_aa: -0.0873
      right_hip_fe: 0.6109
      right_knee: 0.9076
  idle_9:
    gait_type: walk_like
    joints:
      left_ankle: 0.0436
      left_hip_aa: -0.0873
      left_hip_fe: 0.6109
      left_knee: 0.9076
      right_ankle: 0.0436
      right_hip_aa: 0.1222
      right_hip_fe: -0.0873
      right_knee: 0.0
    idle_1:
      gait_type: walk_like
      joints:
        left_ankle: 0.0436
        left_hip_aa: 0.0873
        left_hip_fe: -0.0873
        left_knee: 0.0
        right_ankle: 0.1309
        right_hip_aa: -0.0524
        right_hip_fe: 0.5236
        right_knee: 0.8203
    idle_10:
      gait_type: walk_like
      joints:
        left_ankle: 0.0436
        left_hip_aa: 0.0
        left_hip_fe: -0.0873
        left_knee: 0.0
        right_ankle: 0.0436
        right_hip_aa: 0.0
        right_hip_fe: 0.4014
        right_knee: 0.6981
    idle_11:
      gait_type: walk_like
      joints:
        left_ankle: 0.0436
        left_hip_aa: 0.0
        left_hip_fe: 0.4014
        left_knee: 0.6981
        right_ankle: 0.0436
        right_hip_aa: 0.0
        right_hip_fe: -0.0873
        right_knee: 0.0
    idle_2:
      gait_type: walk_like
      joints:
        left_ankle: 0.0436
        left_hip_aa: 0.0
        left_hip_fe: 1.5708
        left_knee: 1.7453
        right_ankle: 0.0436
        right_hip_aa: 0.0
        right_hip_fe: 1.5708
        right_knee: 1.7453
    idle_3:
      gait_type: walk_like
      joints:
        left_ankle: 0.0436
        left_hip_aa: 0.0
        left_hip_fe: -0.0873
        left_knee: 0.0
        right_ankle: 0.0436
        right_hip_aa: 0.0
        right_hip_fe: 0.1745
        right_knee: 0.4363
    MV_ramp_stand:
      gait_type: walk_like
      joints:
        left_ankle: -0.2618
        left_hip_aa: 0.0
        left_hip_fe: -0.0873
        left_knee: 0.0
        right_ankle: -0.2618
        right_hip_aa: 0.0
        right_hip_fe: -0.0873
        right_knee: 0.0