state_estimator:
  ros__parameters:
    joint_estimator:
      links: ["left_origin", "left_ankle", "left_knee", "left_hip_fe"
      , "left_hip_aa", "right_hip_aa", "right_hip_fe"
      ,"right_knee", "right_ankle", "right_origin"]
      base_links: ["left_ankle", "left_knee", "left_hip_fe", "left_hip_aa"
      , "right_hip_aa", "right_hip_fe","right_knee"
      , "right_ankle", "right_origin", "map"]
      #0: X
      #1: Y
      #2: Z
      link_hinge_axis:  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1] 
      link_length_x:    [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      link_length_y:    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] 
      link_length_z:    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] 
      link_mass:        [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      link_com_x:       [0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5]
      link_com_y:       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      link_com_z:       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    cop_estimator:
      names:            ["l_heel_right", "l_heel_left", "l_met1", "l_hallux", "l_met3", "l_toes", "l_met5", "l_arch", "r_heel_right", "r_heel_left", "r_met1", "r_hallux", "r_met3", "r_toes", "r_met5", "r_arch"]
      x_positions:      [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      y_positions:      [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      z_positions:      [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]