state_estimator:
  ros__parameters:
    state_estimator_config:
      # in ms
      refresh_rate : 48

    joint_estimator:
      links: ["left_origin", "left_ankle", "left_knee", "left_hip_fe"
      , "left_hip_aa", "hip_base", "right_hip_aa", "right_hip_fe"
      ,"right_knee", "right_ankle", "right_origin"]
      base_links: ["left_ankle", "left_knee", "left_hip_fe", "left_hip_aa"
      , "hip_base", "right_hip_aa", "right_hip_fe", "right_knee"
      , "right_ankle", "right_origin", "map"]
      link_rotation_axis : [-1.0, 1.0, 1.0, 1.0, 1.0, 1.0, -1.0, 1.0, 1.0, 1.0, 1.0]
#      link_rotation_axis : [-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
#      link_rotation_axis: [ 1.0, -1.0, 1.0, 1.0, 1.0, -1.0, -1.0, 1.0, 1.0, 1.0, 1.0 ]
      #0: X
      #1: Y
      #2: Z
      link_hinge_axis:  [1, 1, 1, 1, 2, 0, 1, 1, 1, 1] 
      link_length_x:    [-0.23, 0.0,    0.0,     -0.182, -0.021, 0.021,  0.182, 0.0,   0.0,    0.23, -0.23]
      link_length_y:    [0.0,  0.037, 0.06,    -0.182, -0.08, -0.08, -0.182, 0.06, 0.037, 0.0,   0.0] 
      link_length_z:    [0.138,   0.414, 0.413,   0.0, -0.025,   0.025,  0.0,   -0.413, -0.414,  -0.138,   0.0] 
      link_mass:        [0.0, 1.22, 4.159, 8.566, 1.277, 11.02, 0.0, 1.277, 8.566, 4.159, 1.22]
      link_com_x:       [0.0, 0.033, -0.034, 0.0,    0.065, 0.013, 0.065,  0.0,   -0.034, 0.033,  0.0]
      link_com_y:       [0.0, -0.041, -0.04, -0.034, 0.112, 0.0,   -0.112, 0.034, 0.04,  0.041, 0.0]
      link_com_z:       [0.0, -0.08, -0.223, -0.206, 0.0,   0.24,  0.0,   -0.206, -0.223, -0.08,  0.0]
      link_base_val:    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    cop_estimator:
      # The sensor locations are given relative to their respective attached feet frame
      names:            ["l_heel_right", "l_heel_left", "l_met1", "l_hallux", "l_met3", "l_toes", "l_met5", "l_arch", "r_heel_right", "r_heel_left", "r_met1", "r_hallux", "r_met3", "r_toes", "r_met5", "r_arch"]
      x_positions:      [-0.045, -0.045,  0.137,  0.184,  0.130,  0.174,  0.118,  0.050,    -0.045, -0.045,  0.137,  0.184,  0.130,  0.174,  0.118,  0.050]
      y_positions:      [-0.072, -0.098, -0.115, -0.105, -0.083, -0.070, -0.050, -0.061,     0.072,  0.098,  0.115,  0.105,  0.083,  0.070,  0.050, 0.061]
      z_positions:      [-0.138, -0.138, -0.138, -0.138, -0.138, -0.138, -0.138, -0.138,    -0.138, -0.138, -0.138, -0.138, -0.138, -0.138, -0.138, -0.138,]
      #In radians
      starting_position: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    imu_estimator:
      lower_imu:
        #IMU stuff
        IMU_exo_base_link: "hip_base"
          #POS: X, Y, Z
        IMU_exo_position: [0.0, 0.0, 0.0]
        IMU_exo_rotation: [0.0, 0.0, 0.0]
      upper_imu:
        IMU_exo_base_link: "hip_base"
          #POS: X, Y, Z
        IMU_exo_position: [0.0, 0.0, -0.5]
        IMU_exo_rotation: [0.0, 0.0, 0.0]
    footstep_estimator:
      left_foot:
        #SIZE: WIDTH, HEIGHT
        size: [1.0,1.0]
      right_foot:
        #SIZE: WIDTH, HEIGHT
        size: [1.0,1.0]
      on_ground_threshold: 0.5
