gaits:
  balance_walk:
    left_close: MV_walk_leftclose_v2
    left_swing_1: MV_balancewalk_leftswing1_v2
    left_swing_2: MV_balancewalk_leftswing2_v2
    right_close: MV_walk_rightclose_v2
    right_open_1: MV_balancewalk_rightopen1_v6_4
    right_open_2: MV_balancewalk_rightopen2_v6_3
    right_swing_1: MV_balancewalk_rightswing1_v2
    right_swing_2: MV_balancewalk_rightswing2_v2
  walk:
    left_close: MV_walk_leftclose_v2
    left_close_large: MV_walklarge_leftclose_v1
    left_close_small: MV_walksmall_leftclose_v1
    left_swing: MV_walk_leftswing_v2
    left_swing_large: MV_walklarge_leftswing_v1
    left_swing_small: MV_walksmall_leftswing_v1
    right_close: MV_walk_rightclose_v2
    right_close_large: MV_walklarge_rightclose_v1
    right_close_small: MV_walksmall_rightclose_v1
    right_open: MV_walk_rightopen_v2
    right_swing: MV_walk_rightswing_v2
    right_swing_large: MV_walklarge_rightswing_v1
    right_swing_small: MV_walksmall_rightswing_v1
positions:
  stand:
    gait_type: walk_like
    joints:
      left_ankle: 0.0
      left_hip_aa: 0.0349
      left_hip_fe: -0.1745
      left_knee: 0.0
      right_ankle: 0.0
      right_hip_aa: 0.0349
      right_hip_fe: -0.1745
      right_knee: 0.0

