#!/usr/bin/env python
import rospy
import math
from tf import TransformListener, LookupException, ConnectivityException, ExtrapolationException
from march_shared_resources.msg import FeetDistances

rospy.init_node('feet_transformer')
listener = TransformListener()
feet_distances = rospy.Publisher('feet_distances', FeetDistances, queue_size=10)

rate = rospy.Rate(10.0)
while not rospy.is_shutdown():
    try:
        (trans_right, rot_right) = listener.lookupTransform('/foot_right', '/foot_left', rospy.Time(0))
        (trans_left, rot_left) = listener.lookupTransform('/foot_left', '/foot_right', rospy.Time(0))
    except (LookupException, ConnectivityException, ExtrapolationException):
        continue

    feet_distances_msg = FeetDistances()
    feet_distances_msg.foot_height_right = trans_right[2]
    feet_distances_msg.foot_height_left = trans_left[2]
    feet_distances_msg.step_distance = math.sqrt(trans_right[0] ** 2 + trans_right[2] ** 2)
    feet_distances.publish(feet_distances_msg)

    rate.sleep()
    
