#!/usr/bin/env python

import sys

from march_rqt_console.console_plugin import ConsolePlugin
from rqt_gui.main import Main

plugin = 'march_rqt_console'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
