controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    update_rate: 1000
    joints:
      - left_ankle
      - left_hip_aa
      - left_hip_fe
      - left_knee
      - right_ankle
      - right_hip_aa
      - right_hip_fe
      - right_knee
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position

