<?xml version="1.0"?>
<robot name="stairs" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <gazebo>
        <static>true</static>
    </gazebo>

    <!-- Sizes from the rules of the cybathlon 2020 -->
    <xacro:property name="step_height" default="0.170"/>
    <xacro:property name="step_depth" default="0.280"/>
    <xacro:property name="stairs_width" default="1.206"/>
    <xacro:property name="stairs_length" default="4.050"/>
    <xacro:property name="distance_to_origin" default="0.4"/>

    <xacro:property name="parent_name" value="world"/>
    <xacro:property name="mu1" value="1.0"/>
    <xacro:property name="mu2" value="1.0"/>
    <!-- Minimum allowable depth before contact correction impulse is applied. -->
    <xacro:property name="min_depth" value="0.0005"/>

    <!-- Used for fixing robot to Gazebo 'base_link' -->
    <link name="${parent_name}"/>


    <!-- Links -->
    <link name="step_1">
        <collision>
          <geometry>
            <box size="${stairs_length} ${stairs_width} ${step_height}" />
          </geometry>
        </collision>

        <visual name='visual'>
          <geometry>
            <box size="${stairs_length} ${stairs_width} ${step_height}" />
          </geometry>
        </visual>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="1"/>
            <inertia
                    ixx="1"
                    ixy="1"
                    ixz="1"
                    iyy="1"
                    iyz="1"
                    izz="1" />
        </inertial>
    </link>

    <link name="step_2">
        <collision>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
            <box size="${stairs_length - 2 * step_depth} ${stairs_width} ${step_height}" />
          </geometry>
        </collision>

        <visual name='visual'>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
            <box size="${stairs_length - 2 * step_depth} ${stairs_width} ${step_height}" />
          </geometry>
        </visual>
    </link>

    <link name="step_3">
        <collision>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
            <box size="${stairs_length - 4 * step_depth} ${stairs_width} ${step_height}" />
          </geometry>
        </collision>

        <visual name='visual'>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
            <box size="${stairs_length - 4 * step_depth} ${stairs_width} ${step_height}" />
          </geometry>
        </visual>
    </link>

    <link name="step_4">
        <collision>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
            <box size="${stairs_length - 6 * step_depth} ${stairs_width} ${step_height}" />
          </geometry>
        </collision>

        <visual name='visual'>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
            <box size="${stairs_length - 6 * step_depth} ${stairs_width} ${step_height}" />
          </geometry>
        </visual>
    </link>

    <link name="step_5">
        <collision>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
            <box size="${stairs_length - 8 * step_depth} ${stairs_width} ${step_height}" />
          </geometry>
        </collision>

        <visual name='visual'>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
            <box size="${stairs_length - 8 * step_depth} ${stairs_width} ${step_height}" />
          </geometry>
        </visual>
    </link>

    <link name="step_6">
        <collision>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
            <box size="${stairs_length - 10 * step_depth} ${stairs_width} ${step_height}" />
          </geometry>
        </collision>

        <visual name='visual'>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
            <box size="${stairs_length - 10 * step_depth} ${stairs_width} ${step_height}" />
          </geometry>
        </visual>
    </link>

    <gazebo reference="step_1">
        <mu1>${mu1}</mu1>
        <mu2>${mu2}</mu2>
        <minDepth>${min_depth}</minDepth>
    </gazebo>

    <gazebo reference="step_2">
        <mu1>${mu1}</mu1>
        <mu2>${mu2}</mu2>
        <minDepth>${min_depth}</minDepth>
    </gazebo>

    <gazebo reference="step_3">
        <mu1>${mu1}</mu1>
        <mu2>${mu2}</mu2>
        <minDepth>${min_depth}</minDepth>
    </gazebo>

    <gazebo reference="step_4">
        <mu1>${mu1}</mu1>
        <mu2>${mu2}</mu2>
        <minDepth>${min_depth}</minDepth>
    </gazebo>

    <gazebo reference="step_5">
        <mu1>${mu1}</mu1>
        <mu2>${mu2}</mu2>
        <minDepth>${min_depth}</minDepth>
    </gazebo>

    <gazebo reference="step_6">
        <mu1>${mu1}</mu1>
        <mu2>${mu2}</mu2>
        <minDepth>${min_depth}</minDepth>
    </gazebo>

    <!-- Joints -->
    <joint name="hip" type="fixed">
        <parent link="${parent_name}"/>
        <child link="step_1"/>
        <origin xyz="${-distance_to_origin - stairs_length / 2} 0 ${step_height / 2}" rpy="0 0 0"/>
    </joint>

    <joint name="joint_1" type="fixed">
        <parent link="step_1"/>
        <child link="step_2"/>
        <origin xyz="0 0 ${step_height}" rpy="0 0 0"/>
    </joint>

    <joint name="joint_2" type="fixed">
        <parent link="step_2"/>
        <child link="step_3"/>
        <origin xyz="0 0 ${step_height}" rpy="0 0 0"/>
    </joint>

    <joint name="joint_3" type="fixed">
        <parent link="step_3"/>
        <child link="step_4"/>
        <origin xyz="0 0 ${step_height}" rpy="0 0 0"/>
    </joint>

    <joint name="joint_4" type="fixed">
        <parent link="step_4"/>
        <child link="step_5"/>
        <origin xyz="0 0 ${step_height}" rpy="0 0 0"/>
    </joint>

    <joint name="joint_5" type="fixed">
        <parent link="step_5"/>
        <child link="step_6"/>
        <origin xyz="0 0 ${step_height}" rpy="0 0 0"/>
    </joint>

</robot>