gaits:
  ramp_up:
    left_close: MVI_rampup_leftclose_steep_v2
    left_open: MVI_rampup_leftopen_steep_v2
    left_swing: MVI_rampup_leftswing_steep_v2
    right_close: MVI_rampup_rightclose_steep_v2
    right_open: MVI_rampup_rightopen_steep_v2
    right_swing: MVI_rampup_rightswing_steep_v2

  ramp_down:
    left_close: MVI_rampdown_leftclose_steep_v2
    left_open: MVI_rampdown_leftopen_steep_v2
    left_swing: MVI_rampdown_leftswing_steep_v2
    right_close: MVI_rampdown_rightclose_steep_v2
    right_open: MVI_rampdown_rightopen_steep_v2
    right_swing: MVI_rampdown_rightswing_steep_v2

  ramp_down_last_step:
    left_close: MVI_rampdownlaststep_leftclose_steep_v1
    right_open: MVI_rampdownlaststep_rightopen_steep_v1

  stairs_up:
    left_close: MVI_stairsup_leftclose_cybathlon_v4
    left_swing: MVI_stairsup_leftswing_cybathlon_v4
    right_close: MVI_stairsup_rightclose_cybathlon_v4
    right_open: MVI_stairsup_rightopen_cybathlon_v4
    right_swing: MVI_stairsup_rightswing_cybathlon_v4

  stairs_up_single_step:
    right_open: MVI_stairsupsinglestep_rightopen_cybathlon_v4
    left_close: MVI_stairsupsinglestep_leftclose_cybathlon_v4

  stairs_down:
    left_close: MVI_stairsdown_leftclose_cybathlon_v2
    left_swing: MVI_stairsdown_leftswing_cybathlon_v2
    right_close: MVI_stairsdown_rightclose_cybathlon_v2
    right_open: MVI_stairsdown_rightopen_cybathlon_v2
    right_swing: MVI_stairsdown_rightswing_cybathlon_v2

  stairs_down_single_step:
    left_close: MVI_stairsdownsinglestep_leftclose_cybathlon_v2
    right_open: MVI_stairsdownsinglestep_rightopen_cybathlon_v2

  stairs_down_backwards:
    left_close: MVI_stairsdownbackwards_leftclose_cybathlon_v2
    left_swing: MVI_stairsdownbackwards_leftswing_cybathlon_v2
    right_close: MVI_stairsdownbackwards_rightclose_cybathlon_v2
    right_open: MVI_stairsdownbackwards_rightopen_cybathlon_v2
    right_swing: MVI_stairsdownbackwards_rightswing_cybathlon_v2

  stairs_down_backwards_single_step:
    left_close: MVI_stairsdownbackwardssinglestep_leftclose_cybathlon_v2
    right_open: MVI_stairsdownbackwardssinglestep_rightopen_cybathlon_v2

  walk:
    left_close: MVI_walk_leftclose_v6
    left_swing: MVI_walk_leftswing_v6
    right_close: MVI_walk_rightclose_v6
    right_open: MVI_walk_rightopen_v6
    right_swing: MVI_walk_rightswing_v6

  walk_single_step:
    right_open: MVI_walksinglestep_rightopen_v3
    left_close: MVI_walksinglestep_leftclose_v3
  
  walk_large:
    left_close: MVI_walklarge_leftclose_v3
    left_swing: MVI_walklarge_leftswing_v3
    right_close: MVI_walklarge_rightclose_v3
    right_open: MVI_walklarge_rightopen_v3
    right_swing: MVI_walklarge_rightswing_v3

  walk_single_step_large:
    right_open: MVI_walksinglesteplarge_rightopen_v3
    left_close: MVI_walksinglesteplarge_leftclose_v3
 
  walk_small:
    left_close: MVI_walksmall_leftclose_v3
    left_swing: MVI_walksmall_leftswing_v3
    right_close: MVI_walksmall_rightclose_v3
    right_open: MVI_walksmall_rightopen_v3
    right_swing: MVI_walksmall_rightswing_v3
    
  sit:
    sit_down: MVI_sit_down_v2
    sit_home: MVI_sit_home_v2
    prepare_sit_down: MVI_prepare_sit_down_v2
  
  stand:
    prepare_stand_up: MVI_prepare_stand_up_v2
    stand_up: MVI_stand_up_v2
    stand_home: MVI_stand_home_v2

  walk_single_step_small:
    right_open: MVI_walksinglestepsmall_rightopen_v3
    left_close: MVI_walksinglestepsmall_leftclose_v3

  sit:
    sit_down: MVI_sit_down_v2
    sit_home: MVI_sit_home_v2
    prepare_sit_down: MVI_prepare_sit_down_v2

  stand:
    prepare_stand_up: MVI_prepare_stand_up_v2
    stand_up: MVI_stand_up_v2
    stand_home: MVI_stand_home_v2

positions:
  stand:
    gait_type: walk_like
    joints:
      left_ankle: 0.0
      left_hip_aa: 0.0349
      left_hip_fe: 0.0
      left_knee: 0.0
      right_ankle: 0.0
      right_hip_aa: 0.0349
      right_hip_fe: 0.0
      right_knee: 0.0

  flat_ramp_stand:
    gait_type: walk_like
    joints:
      left_ankle: -0.0873
      left_hip_aa: 0.0349
      left_hip_fe: -0.0873
      left_knee: 0.0
      right_ankle: -0.0873
      right_hip_aa: 0.0349
      right_hip_fe: -0.0873
      right_knee: 0.0
  steep_ramp_stand:
    gait_type: walk_like
    joints:
      left_ankle: -0.2618
      left_hip_aa: 0.0349
      left_hip_fe: -0.0873
      left_knee: 0.0
      right_ankle: -0.2618
      right_hip_aa: 0.0349
      right_hip_fe: -0.0873
      right_knee: 0.0
  sit_without_haa:
    gait_type: sit_like
    joints:
      left_ankle: 0.0
      left_hip_aa: 0.0349
      left_hip_fe: 1.4835
      left_knee: 1.4835
      right_ankle: 0.0
      right_hip_aa: 0.0349
      right_hip_fe: 1.4835
      right_knee: 1.4835
  sit_with_haa:
    gait_type: sit_like
    joints:
      left_ankle: 0.0
      left_hip_aa: 0.0
      left_hip_fe: 1.4835
      left_knee: 1.4835
      right_ankle: 0.0
      right_hip_aa: 0.0
      right_hip_fe: 1.4835
      right_knee: 1.4835
