<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="march" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- Constants for robot dimensions -->
    <xacro:property name="joint_base_mass" value="1"/> <!-- arbitrary value for joint_base_mass -->
    <xacro:property name="joint_base_width" value="0.05"/> <!-- Cube dimensions (width x width x width) of joint base -->

    <xacro:property name="bar_length" value="0.39"/>
    <xacro:property name="bar_mass" value="1.080"/>
    <xacro:property name="bar_width" value="0.05"/>

    <xacro:property name="hover_height" value="0.5"/>

    <xacro:arg name="configuration" default="exoskeleton"/>
    <xacro:property name="configuration" value="$(arg configuration)"/>

    <!-- Include all macro files    -->
    <xacro:include filename="../macros/safety_limits.xacro"/>
    <xacro:include filename="../macros/pressure_sole.xacro"/>
    <xacro:include filename="../macros/frame_part.xacro"/>
    <xacro:include filename="../macros/joint.xacro"/>
    <xacro:include filename="../macros/configurable_joint.xacro"/>


    <!-- Add yaml files with properties -->
    <xacro:property name="config_yaml_file"
                    value="properties/test_joints.yaml"/>
    <xacro:property name="properties" value="${load_yaml(config_yaml_file)}"/>
    <xacro:property name="joint_limits" value="${properties['joint_limits']}"/>
    <xacro:property name="safety_values"
                    value="${properties['safety'][configuration]}"/>
    <xacro:property name="inertia" value="${properties['inertia']}"/>
    <xacro:property name="dimensions" value="${properties['dimensions']}"/>

    <!-- Harmonic Drive: 101, Belt: 1,2-->
    <xacro:property name="rotary_reduction" value="${101 * 1.2}"/>

    <xacro:property name="actuating_joints" value="${(properties['actuating_joints'])}"/>

    <!-- Used for fixing robot to Gazebo 'base_link' -->
    <link name="world"/>

    <joint name="joint_base_fixed_parent_joint" type="fixed">
        <parent link="world"/>
        <child link="joint_base"/>
        <origin xyz="0 0 ${hover_height}" rpy="0 0 0"/>
    </joint>

    <xacro:march_configurable_joint
            name="rotational_joint"
            parent="joint_base"
            child="bar"
            safety="${safety_values['rotational_joint']}"
            origin="0 ${-joint_base_width} 0"
            axis="0 1 0"
            reduction="${rotary_reduction}"
            limits="${joint_limits['rotational_joint']}"
    />

    <!-- give colors to some links in gazebo -->
    <gazebo reference="joint_base">
        <material>Gazebo/Blue</material>
    </gazebo>


    <!-- Joint Base-->
    <link name="joint_base">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${joint_base_width} ${joint_base_width} ${joint_base_width}"/>
            </geometry>
        </visual>

        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${joint_base_mass}"/>
            <inertia
                    ixx="${joint_base_mass / 12.0 * (2*(joint_base_width*joint_base_width))}" ixy="0.0" ixz="0.0"
                    iyy="${joint_base_mass / 12.0 * (2*(joint_base_width*joint_base_width))}" iyz="0.0"
                    izz="${joint_base_mass / 12.0 * (2*(joint_base_width*joint_base_width))}"/>
        </inertial>
    </link>

    <!-- Bar-->
    <link name="bar">
        <visual>
            <origin xyz="0 0 ${-bar_length/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${bar_width} ${bar_width} ${bar_length}"/>
            </geometry>
        </visual>

        <inertial>
            <origin xyz="0 0 ${-bar_length/2}" rpy="0 0 0"/>
            <mass value="${bar_mass}"/>
            <inertia
                    ixx="${joint_base_mass / 12.0 * (bar_width*bar_width + bar_length*bar_length)}" ixy="0.0" ixz="0.0"
                    iyy="${joint_base_mass / 12.0 * (bar_length*bar_length + bar_width*bar_width)}" iyz="0.0"
                    izz="${joint_base_mass / 12.0 * (bar_width*bar_width + bar_width*bar_width)}"/>
        </inertial>
    </link>
</robot>
