controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    update_rate: 1000
    joints:
      - left_ankle
      - left_hip_aa
      - left_hip_fe
      - left_knee
      - right_ankle
      - right_hip_aa
      - right_hip_fe
      - right_knee
    interface_name: position
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    gains:
      left_ankle: { p: 500.0, i: 0.0, d: 10.0, i_clamp: 0.0 }
      left_hip_aa: { p: 5000.0, i: 0.0, d: 100.0, i_clamp: 0.0  }
      left_hip_fe: { p: 5000.0, i: 0.0, d: 100.0, i_clamp: 0.0 }
      left_knee: { p: 5000.0, i: 0.0, d: 100.0, i_clamp: 0.0 }
      right_ankle: { p: 500.0, i: 0.0, d: 10.0, i_clamp: 0.0 }
      right_hip_aa: { p: 5000.0, i: 0.0, d: 100.0, i_clamp: 0.0 }
      right_hip_fe: { p: 5000.0, i: 0.0, d: 100.0, i_clamp: 0.0 }
      right_knee: { p: 5000.0, i: 0.0, d: 100.0, i_clamp: 0.0  }

    state_publish_rate: 1000.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
#    open_loop_control: false
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)
