bounds:
  # all values represent height in meters
  lower_bound: 0.0
  upper_bound: 0.05 # interpolate up to 5cm
joints:
  # all values represent ratios in percentage points
  left_ankle:
    minimum_torque: 0.7
    maximum_torque: 0.7 # 70% position 30% torque
  left_hip_aa:
    minimum_torque: 0.0
    maximum_torque: 0.0 # 100% position 0% torque
  left_hip_fe:
    minimum_torque: 0.0
    maximum_torque: 0.0 # 100% position 0% torque
  left_knee:
    minimum_torque: 0.0
    maximum_torque: 0.0 # 90% position 10% torque
  right_ankle:
    minimum_torque: 0.7
    maximum_torque: 0.7 # 70% position 30% torque
  right_hip_aa:
    minimum_torque: 0.0
    maximum_torque: 0.0 # 100% position 0% torque
  right_hip_fe:
    minimum_torque: 0.0
    maximum_torque: 0.0 # 100% position 0% torque
  right_knee:
    minimum_torque: 0.0
    maximum_torque: 0.0 # 90% position 10% torque
