bounds:
  lower_bound: 0.1
  upper_bound: 0.2
joints:
  left:
    left_ankle:
      minimum_torque: 0.0
      maximum_torque: 0.1
    left_hip_aa:
      minimum_torque: 0.0
      maximum_torque: 0.1
    left_hip_fe:
      minimum_torque: 0.0
      maximum_torque: 0.1
    left_knee:
      minimum_torque: 0.0
      maximum_torque: 0.1
  right:
    right_ankle:
      minimum_torque: 0.0
      maximum_torque: 0.1
    right_hip_aa:
      minimum_torque: 0.0
      maximum_torque: 0.1
    right_hip_fe:
      minimum_torque: 0.0
      maximum_torque: 0.1
    right_knee:
      minimum_torque: 0.0
      maximum_torque: 0.1
  rotational_joint:
    minimum_torque: 0.0
    maximum_torque: 0.1
  linear_joint:
    minimum_torque: 0.0
    maximum_torque: 0.1
  
