backpack:
  angular:
    acceleration:
      m00: '0'
      m10: '0'
      m20: '0'
    velocity:
      m00: '0'
      m10: '0'
      m20: '0'
  axis:
  - 0
  - 0
  - 0
  children:
  - bar
  dynamics:
    inertia: '0'
    mass: 0.3743
    torque:
      m00: -0.336330734594*ddq_bar-1.6534714779*sqrt(2)*cos(q_bar+Pi/4)
  jacobian:
    position:
      m00: '0'
      m10: '0'
      m20: '0'
    rotation:
      m00: '0'
      m10: '0'
      m20: '0'
  joint_names:
    absolute: []
    relative:
    - bar
  linear:
    acceleration:
      m00: '0'
      m10: '0'
      m20: '0'
    position:
      m00: '0'
      m10: '0'
      m20: '0'
    velocity:
      m00: '0'
      m10: '0'
      m20: '0'
  name: backpack
  parent: ''
  rotation:
    m00: '1.00000000000000'
    m01: '0'
    m02: '0'
    m10: '0'
    m11: '1.00000000000000'
    m12: '0'
    m20: '0'
    m21: '0'
    m22: '1.00000000000000'
  type: mass
bar:
  angular:
    acceleration:
      m00: '0'
      m10: ddq_bar
      m20: '0'
    velocity:
      m00: '0'
      m10: dq_bar
      m20: '0'
  axis:
  - 0.0
  - 1.0
  - 0.0
  children:
  - weight
  dynamics:
    inertia: '0.336330734594000'
    mass: 0.0
    torque:
      m00: '0'
  jacobian:
    position:
      m00: '0'
      m10: '0'
      m20: '0'
    rotation:
      m00: '0'
      m10: '0'
      m20: '0'
  joint_names:
    absolute:
    - bar
    relative: []
  linear:
    acceleration:
      m00: '0'
      m10: '0'
      m20: '0'
    position:
      m00: '0'
      m10: '0'
      m20: '0'
    velocity:
      m00: '0'
      m10: '0'
      m20: '0'
  name: bar
  parent: backpack
  rotation:
    m00: cos(q_bar)
    m01: '0'
    m02: sin(q_bar)
    m10: '0'
    m11: '1.00000000000000'
    m12: '0'
    m20: -sin(q_bar)
    m21: '0'
    m22: cos(q_bar)
  type: joint
names:
- backpack
- weight
- bar
weight:
  angular:
    acceleration:
      m00: '0'
      m10: ddq_bar
      m20: '0'
    velocity:
      m00: '0'
      m10: dq_bar
      m20: '0'
  axis:
  - 0
  - 0
  - 0
  children: []
  dynamics:
    inertia: '0'
    mass: 0.7073
    torque:
      m00: '0'
  jacobian:
    position:
      m00: 0.2383*sqrt(2)*sin(q_bar+Pi/4)
      m10: '0'
      m20: 0.2383*sqrt(2)*cos(q_bar+Pi/4)
    rotation:
      m00: '0'
      m10: '0'
      m20: '0'
  joint_names:
    absolute:
    - bar
    relative: []
  linear:
    acceleration:
      m00: 0.2383*sqrt(2)*(ddq_bar*sin(q_bar+Pi/4)+dq_bar^2*cos(q_bar+Pi/4))
      m10: '0'
      m20: 0.2383*sqrt(2)*(ddq_bar*cos(q_bar+Pi/4)-dq_bar^2*sin(q_bar+Pi/4))
    position:
      m00: -0.2383*sqrt(2)*cos(q_bar+Pi/4)
      m10: '0'
      m20: 0.2383*sqrt(2)*sin(q_bar+Pi/4)
    velocity:
      m00: 0.2383*sqrt(2)*dq_bar*sin(q_bar+Pi/4)
      m10: '0'
      m20: 0.2383*sqrt(2)*dq_bar*cos(q_bar+Pi/4)
  name: weight
  parent: bar
  rotation:
    m00: cos(q_bar)
    m01: '0'
    m02: sin(q_bar)
    m10: '0'
    m11: '1.00000000000000'
    m12: '0'
    m20: -sin(q_bar)
    m21: '0'
    m22: cos(q_bar)
  type: mass