state_estimator:
  ros__parameters:
    noise_parameters:
      process_noise:
        linear_acceleration:
        - 1e-5  # x
        - 1e-5  # y
        - 1e-5  # z
        angular_velocity:
        - 1e-12  # roll
        - 1e-12  # pitch
        - 1e-12  # yaw
        foot_position:
        - 1e-12  # x
        - 1e-12  # y
        - 1e-12  # z
        accelerometer_bias:
        - 1e-5  # x
        - 1e-5  # y
        - 1e-5  # z
        gyroscope_bias:
        - 1e-12  # roll
        - 1e-12  # pitch
        - 1e-12  # yaw
        foot_slippage:
        - 1e-12  # roll
        - 1e-12  # pitch
        - 1e-12  # yaw
      observation_noise:
        foot_position:
        - 1e2  # x
        - 1e2  # y
        - 1e2  # z
        foot_slippage:
        - 1e3  # roll
        - 1e3  # pitch
        - 1e3  # yaw
        joint_position:
        - 1e2  # left_hip_aa
        - 1e2  # left_hip_fe
        - 1e2  # left_knee
        - 1e2  # left_ankle_dpf
        - 1e2  # left_ankle_ie
        - 1e2  # right_hip_aa
        - 1e2  # right_hip_fe
        - 1e2  # right_knee
        - 1e2  # right_ankle_dpf
        - 1e2  # right_ankle_ie
    optimization_parameters:
      process_noise:
      - foot_position
      - foot_slippage
      observation_noise:
      - foot_position
      - foot_slippage
      - joint_position