<?xml version="1.0"?>
<robot name="curb" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <gazebo>
        <static>true</static>
    </gazebo>

    <xacro:property name="parent_name" value="world"/>
    <xacro:property name="step_height" default="0.090"/>
    <xacro:property name="step_depth" default="2"/>
    <xacro:property name="step_width" default="1.80"/>
    <xacro:property name="distance_to_origin" default="0.45"/>

    <link name="${parent_name}"/>

    <link name="curb">
        <collision>
          <geometry>
            <box size="${step_depth} ${step_width} ${step_height}" />
          </geometry>
        </collision>

        <visual name='visual'>
          <geometry>
            <box size="${step_depth} ${step_width} ${step_height}" />
          </geometry>
        </visual>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="1"/>
            <inertia
                    ixx="1"
                    ixy="1"
                    ixz="1"
                    iyy="1"
                    iyz="1"
                    izz="1" />
        </inertial>
    </link>

    <joint name="joint_0" type="fixed">
        <parent link="${parent_name}"/>
        <child link="curb"/>
        <origin xyz="${-distance_to_origin - step_depth / 2} 0 ${step_height / 2}" rpy="0 0 0"/>
    </joint>
</robot>
