gaits:
  test_joint_gait:
    perform_test: perform_test_v0
  test_joint_gait_continuous:
    perform_test: perform_test_v0
positions:
  setup:
    gait_type: ''
    joints:
      rotational_joint: 0.0
