# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/pmarch/march/ros1/src/gaits/march_rqt_gait_generator/resource/inverse_kinematics_setpoints_input_dialogue.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_inverse_kinematics_setpoints_input_dialogue(object):
    def setupUi(self, inverse_kinematics_setpoints_input_dialogue):
        inverse_kinematics_setpoints_input_dialogue.setObjectName("inverse_kinematics_setpoints_input_dialogue")
        inverse_kinematics_setpoints_input_dialogue.resize(392, 351)
        self.container = QtWidgets.QFrame(inverse_kinematics_setpoints_input_dialogue)
        self.container.setGeometry(QtCore.QRect(10, 10, 373, 337))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.container.sizePolicy().hasHeightForWidth())
        self.container.setSizePolicy(sizePolicy)
        self.container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.container.setObjectName("container")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.container)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.SetpointInputFrame = QtWidgets.QFrame(self.container)
        self.SetpointInputFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SetpointInputFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SetpointInputFrame.setObjectName("SetpointInputFrame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.SetpointInputFrame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.LeftFootInputFrame = QtWidgets.QFrame(self.SetpointInputFrame)
        self.LeftFootInputFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LeftFootInputFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LeftFootInputFrame.setObjectName("LeftFootInputFrame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.LeftFootInputFrame)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.AxisLabelLeftX = QtWidgets.QLabel(self.LeftFootInputFrame)
        self.AxisLabelLeftX.setObjectName("AxisLabelLeftX")
        self.gridLayout_6.addWidget(self.AxisLabelLeftX, 1, 0, 1, 1)
        self.AxisLabelLeftY = QtWidgets.QLabel(self.LeftFootInputFrame)
        self.AxisLabelLeftY.setObjectName("AxisLabelLeftY")
        self.gridLayout_6.addWidget(self.AxisLabelLeftY, 2, 0, 1, 1)
        self.desired_left_x_input = QtWidgets.QLineEdit(self.LeftFootInputFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.desired_left_x_input.sizePolicy().hasHeightForWidth())
        self.desired_left_x_input.setSizePolicy(sizePolicy)
        self.desired_left_x_input.setObjectName("desired_left_x_input")
        self.gridLayout_6.addWidget(self.desired_left_x_input, 1, 1, 1, 1)
        self.AxisLabelLeftZ = QtWidgets.QLabel(self.LeftFootInputFrame)
        self.AxisLabelLeftZ.setObjectName("AxisLabelLeftZ")
        self.gridLayout_6.addWidget(self.AxisLabelLeftZ, 3, 0, 1, 1)
        self.desired_left_y_input = QtWidgets.QLineEdit(self.LeftFootInputFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.desired_left_y_input.sizePolicy().hasHeightForWidth())
        self.desired_left_y_input.setSizePolicy(sizePolicy)
        self.desired_left_y_input.setObjectName("desired_left_y_input")
        self.gridLayout_6.addWidget(self.desired_left_y_input, 2, 1, 1, 1)
        self.LeftFootLabel = QtWidgets.QLabel(self.LeftFootInputFrame)
        self.LeftFootLabel.setObjectName("LeftFootLabel")
        self.gridLayout_6.addWidget(self.LeftFootLabel, 0, 1, 1, 1)
        self.desired_left_z_input = QtWidgets.QLineEdit(self.LeftFootInputFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.desired_left_z_input.sizePolicy().hasHeightForWidth())
        self.desired_left_z_input.setSizePolicy(sizePolicy)
        self.desired_left_z_input.setObjectName("desired_left_z_input")
        self.gridLayout_6.addWidget(self.desired_left_z_input, 3, 1, 1, 1)
        self.gridLayout_5.addWidget(self.LeftFootInputFrame, 0, 0, 1, 1)
        self.right = QtWidgets.QFrame(self.SetpointInputFrame)
        self.right.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right.setObjectName("right")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.right)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.AxisLabelRightZ = QtWidgets.QLabel(self.right)
        self.AxisLabelRightZ.setObjectName("AxisLabelRightZ")
        self.gridLayout_9.addWidget(self.AxisLabelRightZ, 4, 0, 1, 1)
        self.desired_right_z_input = QtWidgets.QLineEdit(self.right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.desired_right_z_input.sizePolicy().hasHeightForWidth())
        self.desired_right_z_input.setSizePolicy(sizePolicy)
        self.desired_right_z_input.setObjectName("desired_right_z_input")
        self.gridLayout_9.addWidget(self.desired_right_z_input, 4, 1, 1, 1)
        self.desired_right_x_input = QtWidgets.QLineEdit(self.right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.desired_right_x_input.sizePolicy().hasHeightForWidth())
        self.desired_right_x_input.setSizePolicy(sizePolicy)
        self.desired_right_x_input.setObjectName("desired_right_x_input")
        self.gridLayout_9.addWidget(self.desired_right_x_input, 2, 1, 1, 1)
        self.AxisLabelRightX = QtWidgets.QLabel(self.right)
        self.AxisLabelRightX.setObjectName("AxisLabelRightX")
        self.gridLayout_9.addWidget(self.AxisLabelRightX, 2, 0, 1, 1)
        self.desired_right_y_input = QtWidgets.QLineEdit(self.right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.desired_right_y_input.sizePolicy().hasHeightForWidth())
        self.desired_right_y_input.setSizePolicy(sizePolicy)
        self.desired_right_y_input.setObjectName("desired_right_y_input")
        self.gridLayout_9.addWidget(self.desired_right_y_input, 3, 1, 1, 1)
        self.foot_label_right = QtWidgets.QLabel(self.right)
        self.foot_label_right.setObjectName("foot_label_right")
        self.gridLayout_9.addWidget(self.foot_label_right, 1, 1, 1, 1)
        self.AxisLabelRightY = QtWidgets.QLabel(self.right)
        self.AxisLabelRightY.setObjectName("AxisLabelRightY")
        self.gridLayout_9.addWidget(self.AxisLabelRightY, 3, 0, 1, 1)
        self.gridLayout_5.addWidget(self.right, 1, 0, 1, 1)
        self.TimeInputFrame = QtWidgets.QFrame(self.SetpointInputFrame)
        self.TimeInputFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TimeInputFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TimeInputFrame.setObjectName("TimeInputFrame")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.TimeInputFrame)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.AxislabelT = QtWidgets.QLabel(self.TimeInputFrame)
        self.AxislabelT.setObjectName("AxislabelT")
        self.gridLayout_10.addWidget(self.AxislabelT, 1, 0, 1, 1)
        self.time_input = QtWidgets.QLineEdit(self.TimeInputFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_input.sizePolicy().hasHeightForWidth())
        self.time_input.setSizePolicy(sizePolicy)
        self.time_input.setObjectName("time_input")
        self.gridLayout_10.addWidget(self.time_input, 1, 1, 1, 1)
        self.gridLayout_5.addWidget(self.TimeInputFrame, 3, 0, 1, 1)
        self.gridLayout_3.addWidget(self.SetpointInputFrame, 0, 1, 1, 1)
        self.LeftVerticalFrame = QtWidgets.QFrame(self.container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LeftVerticalFrame.sizePolicy().hasHeightForWidth())
        self.LeftVerticalFrame.setSizePolicy(sizePolicy)
        self.LeftVerticalFrame.setObjectName("LeftVerticalFrame")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.LeftVerticalFrame)
        self.vboxlayout.setObjectName("vboxlayout")
        self.AxisExplanationFrame = QtWidgets.QFrame(self.LeftVerticalFrame)
        self.AxisExplanationFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.AxisExplanationFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.AxisExplanationFrame.setObjectName("AxisExplanationFrame")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.AxisExplanationFrame)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label = QtWidgets.QLabel(self.AxisExplanationFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setLineWidth(1)
        self.label.setMidLineWidth(1)
        self.label.setIndent(0)
        self.label.setObjectName("label")
        self.gridLayout_12.addWidget(self.label, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.z_axis_combo_box = QtWidgets.QComboBox(self.AxisExplanationFrame)
        self.z_axis_combo_box.setObjectName("z_axis_combo_box")
        self.gridLayout_12.addWidget(self.z_axis_combo_box, 4, 0, 1, 1)
        self.YAxisExplanationLabel = QtWidgets.QLabel(self.AxisExplanationFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.YAxisExplanationLabel.sizePolicy().hasHeightForWidth())
        self.YAxisExplanationLabel.setSizePolicy(sizePolicy)
        self.YAxisExplanationLabel.setObjectName("YAxisExplanationLabel")
        self.gridLayout_12.addWidget(self.YAxisExplanationLabel, 2, 0, 1, 1)
        self.XAxisExplanationLabel = QtWidgets.QLabel(self.AxisExplanationFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.XAxisExplanationLabel.sizePolicy().hasHeightForWidth())
        self.XAxisExplanationLabel.setSizePolicy(sizePolicy)
        self.XAxisExplanationLabel.setObjectName("XAxisExplanationLabel")
        self.gridLayout_12.addWidget(self.XAxisExplanationLabel, 1, 0, 1, 1)
        self.ZAxisExplanationLabel = QtWidgets.QLabel(self.AxisExplanationFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ZAxisExplanationLabel.sizePolicy().hasHeightForWidth())
        self.ZAxisExplanationLabel.setSizePolicy(sizePolicy)
        self.ZAxisExplanationLabel.setObjectName("ZAxisExplanationLabel")
        self.gridLayout_12.addWidget(self.ZAxisExplanationLabel, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.vboxlayout.addWidget(self.AxisExplanationFrame)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vboxlayout.addItem(spacerItem)
        self.SetSetpointsFrame = QtWidgets.QFrame(self.LeftVerticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SetSetpointsFrame.sizePolicy().hasHeightForWidth())
        self.SetSetpointsFrame.setSizePolicy(sizePolicy)
        self.SetSetpointsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SetSetpointsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SetSetpointsFrame.setObjectName("SetSetpointsFrame")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.SetSetpointsFrame)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.create_inverse_kinematics_setpoints_button = QtWidgets.QPushButton(self.SetSetpointsFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_inverse_kinematics_setpoints_button.sizePolicy().hasHeightForWidth())
        self.create_inverse_kinematics_setpoints_button.setSizePolicy(sizePolicy)
        self.create_inverse_kinematics_setpoints_button.setObjectName("create_inverse_kinematics_setpoints_button")
        self.gridLayout_11.addWidget(self.create_inverse_kinematics_setpoints_button, 0, 0, 1, 1)
        self.vboxlayout.addWidget(self.SetSetpointsFrame)
        self.gridLayout_3.addWidget(self.LeftVerticalFrame, 0, 0, 1, 1)

        self.retranslateUi(inverse_kinematics_setpoints_input_dialogue)
        QtCore.QMetaObject.connectSlotsByName(inverse_kinematics_setpoints_input_dialogue)

    def retranslateUi(self, inverse_kinematics_setpoints_input_dialogue):
        _translate = QtCore.QCoreApplication.translate
        inverse_kinematics_setpoints_input_dialogue.setWindowTitle(_translate("inverse_kinematics_setpoints_input_dialogue", "Dialog"))
        self.AxisLabelLeftX.setText(_translate("inverse_kinematics_setpoints_input_dialogue", "x"))
        self.AxisLabelLeftY.setText(_translate("inverse_kinematics_setpoints_input_dialogue", "y"))
        self.desired_left_x_input.setToolTip(_translate("inverse_kinematics_setpoints_input_dialogue", "<html><head/><body><p><br/></p></body></html>"))
        self.AxisLabelLeftZ.setText(_translate("inverse_kinematics_setpoints_input_dialogue", "z"))
        self.LeftFootLabel.setText(_translate("inverse_kinematics_setpoints_input_dialogue", "left foot"))
        self.AxisLabelRightZ.setText(_translate("inverse_kinematics_setpoints_input_dialogue", "z"))
        self.desired_right_x_input.setToolTip(_translate("inverse_kinematics_setpoints_input_dialogue", "<html><head/><body><p><br/></p></body></html>"))
        self.AxisLabelRightX.setText(_translate("inverse_kinematics_setpoints_input_dialogue", "x"))
        self.foot_label_right.setText(_translate("inverse_kinematics_setpoints_input_dialogue", "right foot"))
        self.AxisLabelRightY.setText(_translate("inverse_kinematics_setpoints_input_dialogue", "y"))
        self.AxislabelT.setText(_translate("inverse_kinematics_setpoints_input_dialogue", "t"))
        self.time_input.setToolTip(_translate("inverse_kinematics_setpoints_input_dialogue", "<html><head/><body><p><br/></p></body></html>"))
        self.label.setText(_translate("inverse_kinematics_setpoints_input_dialogue", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600;\">axes</span></p></body></html>"))
        self.YAxisExplanationLabel.setText(_translate("inverse_kinematics_setpoints_input_dialogue", "y axis is to the right"))
        self.XAxisExplanationLabel.setText(_translate("inverse_kinematics_setpoints_input_dialogue", "x axis is forward"))
        self.ZAxisExplanationLabel.setText(_translate("inverse_kinematics_setpoints_input_dialogue", "z axis: "))
        self.create_inverse_kinematics_setpoints_button.setText(_translate("inverse_kinematics_setpoints_input_dialogue", "Put setpoints in"))
