gaits:
  sit:
    sit_down: MVI_sit_down_v7
    sit_home: MVI_sit_home_v4
    prepare_sit_down: MVI_prepare_sit_down_v6
  stand:
    prepare_stand_up: MVI_prepare_stand_up_v6
    stand_up: MVI_stand_up_v8
    stand_home: MVI_stand_home_v7

positions:
  stand:
    # use v6 for sit and v7 for stand
    gait_type: walk_like
    joints:
      left_ankle: 0.1396
      left_hip_aa: -0.05
      left_hip_fe: 0.12215
      left_knee: 0.1745
      right_ankle: 0.1396
      right_hip_aa: -0.05
      right_hip_fe: 0.12215
      right_knee: 0.1745
  sit:
    gait_type: sit_like
    joints:
      left_ankle: -0.034
      left_hip_aa: -0.05
      left_hip_fe: 1.6451
      left_knee: 1.6452
      right_ankle: -0.034
      right_hip_aa: -0.05
      right_hip_fe: 1.6451
      right_knee: 1.6452
