/*	WARNING: COPYRIGHT (C) 2016 XSENS TECHNOLOGIES OR SUBSIDIARIES WORLDWIDE. ALL RIGHTS RESERVED.
	THIS FILE AND THE SOURCE CODE IT CONTAINS (AND/OR THE BINARY CODE FILES FOUND IN THE SAME
	FOLDER THAT CONTAINS THIS FILE) AND ALL RELATED SOFTWARE (COLLECTIVELY, "CODE") ARE SUBJECT
	TO A RESTRICTED LICENSE AGREEMENT ("AGREEMENT") BETWEEN XSENS AS LICENSOR AND THE AUTHORIZED
	LICENSEE UNDER THE AGREEMENT. THE CODE MUST BE USED SOLELY WITH XSENS PRODUCTS INCORPORATED
	INTO LICENSEE PRODUCTS IN ACCORDANCE WITH THE AGREEMENT. ANY USE, MODIFICATION, COPYING OR
	DISTRIBUTION OF THE CODE IS STRICTLY PROHIBITED UNLESS EXPRESSLY AUTHORIZED BY THE AGREEMENT.
	IF YOU ARE NOT AN AUTHORIZED USER OF THE CODE IN ACCORDANCE WITH THE AGREEMENT, YOU MUST STOP
	USING OR VIEWING THE CODE NOW, REMOVE ANY COPIES OF THE CODE FROM YOUR COMPUTER AND NOTIFY
	XSENS IMMEDIATELY BY EMAIL TO INFO@XSENS.COM. ANY COPIES OR DERIVATIVES OF THE CODE (IN WHOLE
	OR IN PART) IN SOURCE CODE FORM THAT ARE PERMITTED BY THE AGREEMENT MUST RETAIN THE ABOVE
	COPYRIGHT NOTICE AND THIS PARAGRAPH IN ITS ENTIRETY, AS REQUIRED BY THE AGREEMENT.
*/

#include "xsens/pstdint.h"
#include "xsens/xsmessagelist.h"
#include "xsens/xsgpspvtdata.h"
#include "xsens/xstypesconfig.h"
#include "xsens/xsportinfoarray.h"
#include "xsens/xsdebugcounters.h"
#include "xsens/xstimestamp.h"
#include "xsens/xsoutputconfigurationarray.h"
#include "xsens/xscontrolline.h"
#include "xsens/xsoutputsettings.h"
#include "xsens/xsthread.h"
#include "xsens/xspressure.h"
#include "xsens/xsmalloc.h"
#include "xsens/xsmatrix3x3.h"
#include "xsens/xsrawgpssol.h"
#include "xsens/xsvector3.h"
#include "xsens/xsrawgnsssatinfo.h"
#include "xsens/xsoutputconfigurationlist.h"
#include "xsens/xsoutputmode.h"
#include "xsens/xsint64array.h"
#include "xsens/xsmessagearray.h"
#include "xsens/xsrawgpsdop.h"
#include "xsens/xsstring.h"
#include "xsens/xsrssi.h"
#include "xsens/xsdataidentifier.h"
#include "xsens/xsmath.h"
#include "xsens/xsintarray.h"
#include "xsens/xseuler.h"
#include "xsens/xssyncpolarity.h"
#include "xsens/xssyncrole.h"
#include "xsens/xsbaudcode.h"
#include "xsens/xssyncline.h"
#include "xsens/xsbytearray.h"
#include "xsens/xsrawgnsspvtdata.h"
#include "xsens/xsstringarray.h"
#include "xsens/xstriggerindicationdata.h"
#include "xsens/xsstringstreaming.h"
#include "xsens/xssyncsettingarray.h"
#include "xsens/xssdidata.h"
#include "xsens/xsarray.h"
#include "xsens/xsquaternion.h"
#include "xsens/xscalibrateddata.h"
#include "xsens/xsrange.h"
#include "xsens/xsfile.h"
#include "xsens/xsbaud.h"
#include "xsens/xslibraryloader.h"
#include "xsens/xsplatform.h"
#include "xsens/xsanalogindata.h"
#include "xsens/xsdeviceid.h"
#include "xsens/xsrawgpstimeutc.h"
#include "xsens/xstime.h"
#include "xsens/xsversion.h"
#include "xsens/xsintlist.h"
#include "xsens/xsfilepos.h"
#include "xsens/xsexception.h"
#include "xsens/xsmessage.h"
#include "xsens/xsportinfolist.h"
#include "xsens/xssyncsetting.h"
#include "xsens/xsdeviceidlist.h"
#include "xsens/xsvector.h"
#include "xsens/xsrawgpssvinfo.h"
#include "xsens/xsdataformat.h"
#include "xsens/xssimpleversion.h"
#include "xsens/xsatomicint.h"
#include "xsens/xssnapshot.h"
#include "xsens/xsresultvalue.h"
#include "xsens/xstypesinfo.h"
#include "xsens/xsportinfo.h"
#include "xsens/xsushortvector.h"
#include "xsens/xssocket.h"
#include "xsens/xsbaudrate.h"
#include "xsens/xsoutputconfiguration.h"
#include "xsens/xsinforequest.h"
#include "xsens/xstypedefs.h"
#include "xsens/xsdid.h"
#include "xsens/xsbusid.h"
#include "xsens/xsdeviceidarray.h"
#include "xsens/xsmatrix.h"
#include "xsens/xsutctime.h"
#include "xsens/xssyncfunction.h"
#include "xsens/xssyncsettinglist.h"
#include "xsens/xsmutex.h"
#include "xsens/xsxbusmessageid.h"
#include "xsens/xscopy.h"
#include "xsens/xsdatapacket.h"
#include "xsens/xsscrdata.h"
#include "xsens/xsens_compat.h"
