# This enum is used for specifying to which mode of publishing the test publisher should switch.
# All supported modes should be specified here
uint8 START=0
uint8 NEXT=1
uint8 STOP=2
uint8 CUSTOM=3
uint8 selected_mode

# This bool is used to specify the front or back camera
bool use_front_camera

# A string specifying the name of the pointcloud when CUSTUM is the selected mode.
string pointcloud_file_name
---
bool success
