# This enum is used for specifying to which mode of publishing the test publisher should switch.
# All supported modes should be specified here
uint8 NEXT=0
uint8 STOP=1
uint8 CUSTOM=2
uint8 SAVE=3
uint8 selected_mode

# A string specifying the name of the pointcloud when CUSTOM is the selected mode.
string pointcloud_file_name

# From which camera the pointcloud to save comes from, default is front
bool save_camera_back
---
bool success
string message
