joints:
  left_ankle:
    design_points:
      - design_point: 0
        pid_values:
          kp: 15.0
          ki: 0.1
          kd: 0.2
  left_hip_aa:
    design_points:
      - design_point: 0
        pid_values:
          kp: 35.0
          ki: 0.3
          kd: 0.6
  left_hip_fe:
    design_points:
      - design_point: 0
        pid_values:
          kp: 35.0
          ki: 0.5
          kd: 0.4
  left_knee:
    design_points:
      - design_point: 0
        pid_values:
          kp: 20
          ki: 0.2
          kd: 1.5
  right_ankle:  
    design_points:
      - design_point: 0
        pid_values:
          kp: 15.0
          ki: 0.1
          kd: 0.2
  right_hip_aa:
    design_points:
      - design_point: 0
        pid_values:
          kp: 35.0
          ki: 0.3
          kd: 0.6
  right_hip_fe:
    design_points:
      - design_point: 0
        pid_values:
          kp: 35.0
          ki: 0.3
          kd: 0.4
  right_knee:
    design_points:
      - design_point: 0
        pid_values:
          kp: 20.0
          ki: 0.1
          kd: 1.5
