joints:
  linear_joint:
    design_points:
      - design_point: 0
        pid_values:
          kp: 12.0
          ki: 0.0
          kd: 0.2
      - design_point: 0.4
        pid_values:
          kp: 15.0
          ki: 0.1
          kd: 0.3
  rotational_joint:
    design_points:
      - design_point: -.2
        pid_values:
          kp: 11.0
          ki: 0.0
          kd: 0.2
      - design_point: 0
        pid_values:
          kp: 14.0
          ki: 0.1
          kd: 0.3
 