joints:
  left_ankle:
    design_points:
      - design_point: 0
        pid_values:
          kp: 15.0
          ki: 0.1
          kd: 0.2
      - design_point: 1
        pid_values:
          kp: 30.0
          ki: 0.2
          kd: 0.4
  left_hip_aa:
    design_points:
      - design_point: 0
        pid_values:
          kp: 35.0
          ki: 0.3
          kd: 0.6
      - design_point: 1
        pid_values:
          kp: 70.0
          ki: 0.6
          kd: 1.2
  left_hip_fe:
    design_points:
      - design_point: 0
        pid_values:
          kp: 35.0
          ki: 0.5
          kd: 0.4
      - design_point: 1
        pid_values:
          kp: 70.0
          ki: 1
          kd: 0.8
  left_knee:
    design_points:
      - design_point: 0
        pid_values:
          kp: 20
          ki: 0.2
          kd: 1.5
      - design_point: 1
        pid_values:
          kp: 40
          ki: 0.4
          kd: 3.0
  right_ankle:  
    design_points:
      - design_point: 0
        pid_values:
          kp: 15.0
          ki: 0.1
          kd: 0.2
      - design_point: 1
        pid_values:
          kp: 30.0
          ki: 0.2
          kd: 0.4
  right_hip_aa:
    design_points:
      - design_point: 0
        pid_values:
          kp: 35.0
          ki: 0.3
          kd: 0.6
      - design_point: 1
        pid_values:
          kp: 70.0
          ki: 0.6
          kd: 1.2
  right_hip_fe:
    design_points:
      - design_point: 0
        pid_values:
          kp: 35.0
          ki: 0.3
          kd: 0.4
      - design_point: 1
        pid_values:
          kp: 70.0
          ki: 0.6
          kd: 0.8
  right_knee:
    design_points:
      - design_point: 0
        pid_values:
          kp: 20.0
          ki: 0.1
          kd: 1.5
      - design_point: 1
        pid_values:
          kp: 40.0
          ki: 0.2
          kd: 3.0
