string obstacle_name

float64 new_slope_up         # 0 (default value) means default size will be used, this value is defined in the <obstacle>_macro.xacro file
float64 new_slope_down       # 0 (default value)
float64 new_ramp_up_length   # 0 (default value)
---
bool success