gaits:
  sit:
    sit_down: MVI_sit_down_v7
    sit_home: MVI_sit_home_v4
    prepare_sit_down: MVI_prepare_sit_down_v6
  stand:
    prepare_stand_up: MVI_prepare_stand_up_v6
    stand_up: MVI_stand_up_v8
    stand_home: MVI_stand_home_v7

positions:
  stand:
    # use v6 for sit and v7 for stand
    gait_type: walk_like
    joints:
      left_ankle: 0.13
      left_hip_aa: 0.0
      left_hip_fe: 0.09
      left_knee: 0.0
      right_ankle: 0.13
      right_hip_aa: 0.0
      right_hip_fe: 0.09
      right_knee: 0.0
  # stand_hfe_zero_degrees:
  #   # Easier for checking whether hfe's are aligned
  #   gait_type: walk_like
  #   joints:
  #     left_ankle: 0.0
  #     left_hip_aa: 0.0349
  #     left_hip_fe: 0.0
  #     left_knee: 0.0
  #     right_ankle: 0.0
  #     right_hip_aa: 0.0349
  #     right_hip_fe: 0.0
  #     right_knee: 0.0
  sit_without_haa:
    gait_type: sit_like
    joints:
      left_ankle: 0.0
      left_hip_aa: 0.0349
      left_hip_fe: 1.4835
      left_knee: 1.4835
      right_ankle: 0.0
      right_hip_aa: 0.0349
      right_hip_fe: 1.4835
      right_knee: 1.4835
  sit:
    gait_type: sit_like
    joints:
      left_ankle: 0.0
      left_hip_aa: 0.0
      left_hip_fe: 1.6581
      left_knee: 1.5707
      right_ankle: 0.0
      right_hip_aa: 0.0
      right_hip_fe: 1.6581
      right_knee: 1.5707
