#!/usr/bin/env python


from odrive_interface.odrive_motor import OdriveMotor
from odrive_interface.odrive_connection_manager import OdriveConnectionManager


if __name__ == '__main__':
    odrive_connection_manager = OdriveConnectionManager(serial_numbers=['2084387E304E'])
    odrive_motor = OdriveMotor.create_odrive(odrive_connection_manager, '2084387E304E', 'axis0')

    print('odrive 2084387E304E has voltage: {vt}'.format(vt=odrive_motor.voltage))
