march_vision:
  ros__parameters:

    cameras_used: "both" # ["left", "right", "both"]
    left_camera_serial_number: "215222075881" 
    right_camera_serial_number: "033322070612"

    realsense_camera_settings: # the specific parameters for each are in the code
      decimation_filter: true
      spatial_filter: true
      temporal_filter: true
      hole_filling_filter: true
      threshold_filter: false
    
    plane_segmentation: true